/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccesoriosRouteImport } from './routes/accesorios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColeccionSlugRouteImport } from './routes/coleccion.$slug'

const AccesoriosRoute = AccesoriosRouteImport.update({
  id: '/accesorios',
  path: '/accesorios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionSlugRoute = ColeccionSlugRouteImport.update({
  id: '/coleccion/$slug',
  path: '/coleccion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accesorios' | '/coleccion/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accesorios' | '/coleccion/$slug'
  id: '__root__' | '/' | '/accesorios' | '/coleccion/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoriosRoute: typeof AccesoriosRoute
  ColeccionSlugRoute: typeof ColeccionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accesorios': {
      id: '/accesorios'
      path: '/accesorios'
      fullPath: '/accesorios'
      preLoaderRoute: typeof AccesoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion/$slug': {
      id: '/coleccion/$slug'
      path: '/coleccion/$slug'
      fullPath: '/coleccion/$slug'
      preLoaderRoute: typeof ColeccionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoriosRoute: AccesoriosRoute,
  ColeccionSlugRoute: ColeccionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
