/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccesoriosRouteImport } from './routes/accesorios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoriosIndexRouteImport } from './routes/accesorios.index'
import { Route as ColeccionSlugRouteImport } from './routes/coleccion.$slug'
import { Route as AccesoriosTipoRouteImport } from './routes/accesorios.$tipo'

const AccesoriosRoute = AccesoriosRouteImport.update({
  id: '/accesorios',
  path: '/accesorios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoriosIndexRoute = AccesoriosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccesoriosRoute,
} as any)
const ColeccionSlugRoute = ColeccionSlugRouteImport.update({
  id: '/coleccion/$slug',
  path: '/coleccion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoriosTipoRoute = AccesoriosTipoRouteImport.update({
  id: '/$tipo',
  path: '/$tipo',
  getParentRoute: () => AccesoriosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRouteWithChildren
  '/accesorios/$tipo': typeof AccesoriosTipoRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/accesorios/': typeof AccesoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesorios/$tipo': typeof AccesoriosTipoRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/accesorios': typeof AccesoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRouteWithChildren
  '/accesorios/$tipo': typeof AccesoriosTipoRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/accesorios/': typeof AccesoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesorios'
    | '/accesorios/$tipo'
    | '/coleccion/$slug'
    | '/accesorios/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accesorios/$tipo' | '/coleccion/$slug' | '/accesorios'
  id:
    | '__root__'
    | '/'
    | '/accesorios'
    | '/accesorios/$tipo'
    | '/coleccion/$slug'
    | '/accesorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoriosRoute: typeof AccesoriosRouteWithChildren
  ColeccionSlugRoute: typeof ColeccionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accesorios': {
      id: '/accesorios'
      path: '/accesorios'
      fullPath: '/accesorios'
      preLoaderRoute: typeof AccesoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesorios/': {
      id: '/accesorios/'
      path: '/'
      fullPath: '/accesorios/'
      preLoaderRoute: typeof AccesoriosIndexRouteImport
      parentRoute: typeof AccesoriosRoute
    }
    '/coleccion/$slug': {
      id: '/coleccion/$slug'
      path: '/coleccion/$slug'
      fullPath: '/coleccion/$slug'
      preLoaderRoute: typeof ColeccionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesorios/$tipo': {
      id: '/accesorios/$tipo'
      path: '/$tipo'
      fullPath: '/accesorios/$tipo'
      preLoaderRoute: typeof AccesoriosTipoRouteImport
      parentRoute: typeof AccesoriosRoute
    }
  }
}

interface AccesoriosRouteChildren {
  AccesoriosTipoRoute: typeof AccesoriosTipoRoute
  AccesoriosIndexRoute: typeof AccesoriosIndexRoute
}

const AccesoriosRouteChildren: AccesoriosRouteChildren = {
  AccesoriosTipoRoute: AccesoriosTipoRoute,
  AccesoriosIndexRoute: AccesoriosIndexRoute,
}

const AccesoriosRouteWithChildren = AccesoriosRoute._addFileChildren(
  AccesoriosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoriosRoute: AccesoriosRouteWithChildren,
  ColeccionSlugRoute: ColeccionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
